praktika/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontController@index')->name('home');
Route::get('produktai', 'FrontController@produktai');
Route::get('produktas', 'FrontController@produktas');
Route::get('kategorijos', 'FrontController@kategorijos');
Auth::routes();
Route::get('/logout', 'auth\LoginController@logout');

Route::get('admin/edit/{id}', 'FrontController@edit');

Route::get('/home', 'FrontController@index');
Route::resource('/cart', 'CartController');

Route::group(['prefix' => 'admin', 'middleware' =>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
});

?>

praktika/resources/views/admin/layout/includes/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="logo">
                    <h1><a href="{{route('admin.index')}}">Admin</a></h1>
                </div>
            </div>

            <div class="col-md-2 pull-right">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{Auth::user()->name}} <b
                                            class="caret"></b></a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <li><a href="{{url('/')}}">Titulinis</a></li>
                                    <li><a href="{{url('/logout')}}">Atsijungti</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

praktika/resources/views/admin/layout/includes/sidenav.blade.php
{{-- Side Navigation --}}
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block;">
        <ul class="nav">
            
            <li class="current"><a href="{{route('admin.index')}}"><i class="glyphicon glyphicon-home"></i>
                    Valdymas</a></li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Produktai
                    <span class="caret pull-right"></span>
                </a>
                
                <ul>
                    <li><a href="{{route('product.index')}}">Produktai</a></li>
                    <li><a href="{{route('product.create')}}">Prideti produkta</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#">
                    <i class="glyphicon glyphicon-list"></i> Kategorijos
                    <span class="caret pull-right"></span>
                </a>
                
                <ul>
                    <li><a href="{{route('category.index')}}">Kategorijos</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div> 