praktika/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontController@index')->name('home');
Route::get('produktai', 'FrontController@produktai');
Route::get('produktas', 'FrontController@produktas');
Route::get('kategorijos', 'FrontController@kategorijos');
Auth::routes();
Route::get('/logout', 'auth\LoginController@logout');

Route::get('admin/edit/{id}', 'FrontController@edit');

Route::get('/home', 'FrontController@index');
Route::resource('/cart', 'CartController');

Route::group(['prefix' => 'admin', 'middleware' =>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
});

?>

praktika/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Gloudemans\Shoppingcart\Facades\Cart;
use App\Product;
class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cartItems=Cart::content();
        return view('cart.index', compact('cartItems'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $product=Product::find($id);

        Cart::add($id,$product->name,1,$product->price,['size'=>'vidutinis']);

        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Cart::update($id, $request->qty);
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
            Cart::remove($id);
            return back();
    }
}

praktika/resources/views/cart/index.blade.php
@extends('layout.main')
@section('content')

<h3>Krepselis</h3>


<table class="table table-hover">
    <thead>
        <tr>
            
            <th>Pavadinimas</th>
            <th>Kaina</th>
            <th>Kiekis</th>
            <th>Veiksmas</th>
            
        </tr>
    </thead>
    <tbody>
    @foreach($cartItems as $cartItem)
        <tr>
            <td>{{$cartItem->image}}</td>
            <td>{{$cartItem->name}}</td>
            <td>{{$cartItem->price}}</td>
            <td width="100px">
            {!! Form::open(['route' => ['cart.update',$cartItem->rowId], 'method' => 'put']) !!}
            <input name="qty" type="number" value="{{$cartItem->qty}}">
            <input type="submit" class="btn btn-sm btn-default" value="Ok">
            {!! Form::close() !!}
            </td>
            
            
            <td>{{$cartItem->options->has('size')?$cartItem->options->size:''}}</td>

            <td>
                <form action="{{route('cart.destroy',$cartItem->rowId)}}"  method="POST">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                    <input class="button small alert" type="submit" value="Trinti">
                    </form>
            </td>


        </tr>
        @endforeach
        <tr>
            <td></td>
            <td>Viso moketi: {{Cart::subtotal()}}$</td>
            <td>Kiekis: {{Cart::count()}}</td>
        </tr>
    </tbody>
</table>
@endsection