praktika/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'FrontController@index')->name('home');
Route::get('produktai', 'FrontController@produktai');
Route::get('produktas', 'FrontController@produktas');
Route::get('kategorijos', 'FrontController@kategorijos');
Auth::routes();
Route::get('/logout', 'auth\LoginController@logout');

Route::get('admin/edit/{id}', 'FrontController@edit');

Route::get('/home', 'FrontController@index');
Route::resource('/cart', 'CartController');

Route::group(['prefix' => 'admin', 'middleware' =>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
});

?>

praktika/app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FrontController extends Controller
{
    public function index()
    {
        // $produktai=Product::all();
        // return view('front.home',compact('produktai'));
        $produktai = DB::table('products')
        ->offset(0)
        ->limit(4)
        ->orderBy('created_at', 'desc')
        ->get();
return view('front.home',compact('produktai'));
    }

    public function produktai()
    {
        $produktai=Product::all();
        return view('front.produktai', compact('produktai'));
    }

    public function produktas(Product $product)
    {
        $produktai=Product::all();
        return view('front.produktas',compact('product'));
    }

    public function kategorijos()
    {
        $categories=Category::all();
        return view('front.kategorijos',compact('categories'));
    }

    public function edit($id)
    {
        $product=Product::find($id);
        return view('productupdateform')->with('product',$product);
    }
}

praktika/resources/views/front/home.blade.php
@extends('layout.main')

@section('content')
<section class="hero text-center">
            <br/>
            <br/>
            <br/>
            <br/>
            <h2 >
                <strong>
                Sveiki atvyke!
                </strong>
            </h2>
        </section>
        <br/>
        <div class="subheader text-center">
             <h2>
             Naujausi musu produktai
        </h2>
        </div>
       
        
        <div class="row">
            @forelse($produktai as $produktas)
            <div class="small-3 columns">
                <div class="item-wrapper">
                    <div class="img-wrapper">
                        <a href="{{route('cart.edit', $produktas->id)}}" class="button expanded add-to-cart">
                            Prideti
                        </a>
                        <a href="#">
                            <img src="{{url('images', $produktas->image)}}"/>
                        </a>
                    </div>
                    <a href="{{url('/produktas')}}">
                        <h3>
                        {{$produktas->name}}
                        </h3>
                    </a>
                    <h5>
                    {{$produktas->price}}
                    </h5>
                    <p>
                    {{$produktas->size}}
                    </p>
                    <p>
                    {{$produktas->description}}
                    </p>
                </div>
            </div>
            @empty
        <h4>Nera produktu</h4>
            @endforelse
        </div>
        
        <br>
@endsection

praktika/resources/views/front/kategorijos.blade.php
@extends('layout.main')
@section('title', 'Kategorijos')
@section('content')


    <div class="navbar">
        <a class="navbar-brand" href="#">Kategorijos</a>
        <ul class="nav navbar-nav">
            @if(!empty($categories))
            @forelse($categories as $category)
                <li>
                    <a href="{{route('category.show', $category->id)}}">{{$category->name}}</a>
                </li>
            @empty
            <li>Nera duomenu</li>
            @endforelse
        @endif

        </ul>

            </div>
        </div>


    @if(!empty($products))
    <h3>Products</h3>

    <table class="table table-hover">
    	<thead>
    		<tr>
    			<th>Products</th>
    		</tr>
    	</thead>
    	<tbody>
@forelse($products as $product)
    <tr><td>{{$product->name}}</td></tr>
    	@empty
        <tr><td>Nera produktu</td></tr>
        @endforelse

        </tbody>
    </table>
    @endif

@endsection

praktika/resources/views/front/produktai.blade.php
@extends('layout.main')

@section('title', 'Produktai')
@section('content')
       
         <div class="row">
         
         @forelse($produktai as $produktas)
         
            <div class="small-3 columns">
                <div class="item-wrapper">
                    <div class="img-wrapper">
                    <a href="{{route('cart.edit', $produktas->id)}}" class="button expanded add-to-cart">
                            Prideti
                        </a>
                        <a href="#">
                        <img src="{{url('images', $produktas->image)}}"/>
                        </a>
                    </div>
                    <a href="{{url('/produktas')}}">
                        <h3>
                        {{$produktas->name}}
                        </h3>
                    </a>
                    <h5>
                    {{$produktas->price}}
                    </h5>
                    <p>
                    {{$produktas->size}}
                    </p>
                    <p>
                    {{$produktas->description}}
                    </p>
                </div>
            </div>
            @empty
            <h3>Nera produktu</h3>
            @endforelse
    </div>
@endsection

praktika/resources/views/front/produktas.blade.php
@extends('layout.main')
@section('title', 'Produktas')
@section('content')
        <div class="row">
            <div class="small-5 small-offset-1 columns">
                <div class="item-wrapper">
                    <div class="img-wrapper">
                        <a href="#">
                        <img src="{{asset("storage/$product->image")}}"/>
                        </a>
                    </div>
                </div>
            </div>
           )
            <div class="small-6 columns">
                <div class="item-wrapper">
                    <h3 class="subheader">
                       <span class="price-tag">${{$product->price}}</span>
                    </h3>
                    <div class="row">
                        <div class="large-12 columns">
                        
                            <label>
                                Pasirinkite
                                <select>
                                    <option value="small">
                                        Mazas
                                    </option>
                                    <option value="medium">
                                        Vidutinis
                                    </option>
                                    <option value="large">
                                        Didelis
                                    </option>

                                    <p>{!! $product->description !!}
                                    </p>
                                   
                                </select>
                            </label>
                            <a href="#" class="button  expanded">Prideti i krepseli</a>
                        </div>
                    </div>
                <p class="text-left subheader"><small>*Būtinai pasirinkite dydį</small></p>

                </div>
            </div>
        </div>
    </div>
</body>
</html>
@endsection